## Условие 1:
Оформляйте ноутбук, используя эти советы:

Номер задачи - заголовок 2

Номер подзадачи - заголовок 3

Предоставленные наборы данных оформляйте, как код

Рекомендации для преподавателей по оценке задания:
Смотреть, чтобы студент красиво оформлял ноутбук, использовал ячейки с текстом, указывал номера заданий

## Условие 2:
На складе лежат разные фрукты в разном количестве.
Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе

In [1]:
def fruit_sum(my_dict: dict):
    summ = 0
    for num in my_dict.values():
        summ += num
    return summ

In [2]:
fruit = {'Яблоки': 11, 'Груши': 2, 'Персики': 3, 'Бананы': 21, 'Абрикосы': 5, 'Лимоны': 6}
print(fruit_sum(fruit))

48

## Условие 3:
Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты
[100, 125, -90, 345, 655, -1, 0, 200]
Используйте list comprehensions

In [3]:
def clear_list(my_list: list):
    return [i for i in my_list if i >= 0]


price = [100, 125, -90, 345, 655, -1, 0, 200]
new_prc = clear_list(price)
print(new_prc, f'Суммарные расходы: {sum(new_prc)}',sep = '\n')

[100, 125, 345, 655, 0, 200]
Суммарные расходы: 1425

## Условие 4.1:
Даны два списка.

Дата покупки

['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']

Суммы покупок по датам

[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

### 4.1 Найдите, какая выручка у компании в ноябре
Используйте list comprehensions

In [4]:
list_date = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
list_pay = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

list_revenue = [list_pay[i] for i in range(len(list_date)) if (list_date[i].split('-')[1]) == '11']
print("Выручка в ноябре", sum(list_revenue))

Выручка в ноябре 25098

### 4.2 Найдите выручку компании в зависимости от месяца
Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка.

Используйте аннотирование типов.

In [5]:
def report(date: list, pay: list) -> dict:
    summary: dict = {}
    for i in range(len(date)):
        month: str = date[i].split('-')[1]
        summ: int = summary.get(month)
        if summ:
            summary[month]=int(summ) + pay[i]
        else:
            summary.update({month: pay[i]})
    return summary

In [6]:
list_date = ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22',
                 '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23',
                 '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09',
                 '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13',
                 '2021-10-26', '2021-12-09']
list_pay = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930,
                2971,
                6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

print(report(list_date, list_pay))

{'09': 25647, '12': 45452, '10': 28645, '11': 25098}